import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { headers } from "next/headers";

import { Analytics } from "@vercel/analytics/react";
import { getSession } from "next-auth/react";

import TRPCProvider from "@/app/_trpc/Provider";
import { ThemeProvider } from "@/app/_components/providers/theme-provider";
import { cn } from "@/lib/utils";
import NavBar from "./_components/navbar";
import AuthProvider from "./_components/providers/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession({
    req: {
      headers: Object.fromEntries(headers().entries()),
    },
  });

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.className
        )}
      >
        <TRPCProvider>
          <AuthProvider session={session}>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem={true}
            >
              <div className="flex min-h-screen flex-col">
                <NavBar />
                <main className="flex-1 flex flex-col">
                  {children}
                  <Analytics />
                </main>
              </div>
            </ThemeProvider>
          </AuthProvider>
        </TRPCProvider>
      </body>
    </html>
  );
}
